version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
   configuration: src/lm_polygraph/docs/conf.py
   

formats:
   - pdf
   - epub

python:
  install:
    - requirements: src/lm_polygraph/docs/requirements.txt