defaults:
  - polygraph_eval_nmt_norm_default_instruct
  - _self_

dataset: [wmt14, fr-en]
text_column: fr
label_column: en
train_split: train
eval_split: test
few_shot_split: validation
max_new_tokens: 73
translation_ignore_regex: "(?s).*Translation:" 