defaults:
  - polygraph_eval_nmt_norm_default_instruct
  - _self_

dataset: [wmt14, cs-en]
text_column: en
label_column: cs
train_split: train
eval_split: test
few_shot_split: validation
max_new_tokens: 171
translation_ignore_regex: "(?s).*Translation:" 