hydra:
  run:
    dir: ${cache_path}/${task}/${model}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: bloomz-560m
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'

task: qa

dataset: [trivia_qa, rc.nocontext]
text_column: question
label_column: answer
prompt: "Question: {question}\nAnswer:{answer}"
few_shot_split: train
train_split: train
eval_split: validation
max_new_tokens: 20
load_from_disk: false
n_shot: 5
multiref: true
normalize: true
generation_params:
  generate_until:
    - "\n"

train_dataset: null
train_test_split: false
test_split_size: 1

background_train_dataset: allenai/c4
background_train_dataset_text_column: text
background_train_dataset_label_column: url
background_train_dataset_data_files: en/c4-train.00000-of-01024.json.gz
background_load_from_disk: false

subsample_background_train_dataset: 1000
subsample_train_dataset: 1000
subsample_eval_dataset: -1

use_density_based_ue: false
use_seq_ue: false
use_tok_ue: false
use_ens_ue: false
generation_metrics: null
ens_type: 

additional_estimators:
  - module: lm_polygraph.estimators.max_probability
    class_name: MaximumSequenceProbability
    kwargs: {}
  - module: lm_polygraph.estimators.max_probability
    class_name: MaximumSequenceProbabilitySample
    kwargs: {}
  - module: lm_polygraph.estimators.perplexity
    class_name: Perplexity
    kwargs: {}
  - module: lm_polygraph.estimators.perplexity
    class_name: PerplexitySample
    kwargs: {}
  - module: lm_polygraph.estimators.token_entropy
    class_name: MeanTokenEntropy
    kwargs: {}
  - module: lm_polygraph.estimators.token_entropy
    class_name: MeanTokenEntropySample
    kwargs: {}
  - module: lm_polygraph.estimators.pointwise_mutual_information
    class_name: MeanPointwiseMutualInformation
    kwargs: {}
  - module: lm_polygraph.estimators.pointwise_mutual_information
    class_name: MeanPointwiseMutualInformationSample
    kwargs: {}
  - module: lm_polygraph.estimators.conditional_pointwise_mutual_information
    class_name: MeanConditionalPointwiseMutualInformation
    kwargs: {}
  - module: lm_polygraph.estimators.conditional_pointwise_mutual_information
    class_name: MeanConditionalPointwiseMutualInformationSample
    kwargs: {}
  - module: lm_polygraph.estimators.token_sar
    class_name: TokenSAR
    kwargs: {}
  - module: lm_polygraph.estimators.token_sar
    class_name: TokenSARSample
    kwargs: {}

ignore_exceptions: false

batch_size: 1
deberta_batch_size: 10

seed:
    - 1
